/**
 * Project brief — a self-contained markdown summary of one AnalysisRun that a
 * planner can paste into an email, a proposal or a partner's intake form.
 *
 * Pure and deterministic: every figure is read from the run (nothing is
 * recomputed or rounded differently), and the date defaults to the run's own
 * creation time so the same run always renders the same brief.
 */

import type { AnalysisRun, Partner, PartnerFocus } from "@/lib/types";
import { costPerPersonServed } from "@/lib/metrics/cost-per-person";

export type BriefSection = { title: string; body: string };

export type BriefOptions = {
  /** Overrides run.partners (e.g. freshly discovered, or the verified list for older runs). */
  partners?: Partner[];
  /** Extra sections appended before the appendix — e.g. the simulation track. */
  extraSections?: BriefSection[];
  /** Defaults to run.createdAt. */
  generatedAt?: Date;
};

const PROVENANCE_LABEL: Record<AnalysisRun["provenance"], string> = {
  live: "live analysis",
  cache: "saved live analysis (replayed)",
  demo: "bundled demo snapshot",
};

const EVIDENCE_LABEL = {
  live: "live Exa search during this run",
  snapshot: "a saved earlier live Exa search",
  bundled: "bundled reference sources (no live search was run)",
} as const;

const FOCUS_LABEL: Record<PartnerFocus, string> = {
  boreholes: "boreholes",
  handpumps: "handpumps",
  solar_pumping: "solar pumping",
  piped_schemes: "piped schemes",
  rainwater: "rainwater",
  water_quality: "water quality",
  maintenance: "maintenance",
  sanitation: "sanitation",
  funding: "funding",
  policy: "policy",
  emergency: "emergency",
};

const usd = (n: number) => `$${Math.round(n).toLocaleString("en-US")}`;
const num = (n: number) => Math.round(n).toLocaleString("en-US");
const pct = (x: number) => `${Math.round(x * 100)}%`;

/** Escape characters that would break a markdown table cell or inline text. */
function cell(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

function link(label: string, url: string): string {
  const safeUrl = url.replace(/\(/g, "%28").replace(/\)/g, "%29").replace(/\s/g, "%20");
  return `[${label.replace(/[[\]]/g, "")}](${safeUrl})`;
}

function table(header: string[], rows: string[][]): string {
  return [
    `| ${header.map(cell).join(" | ")} |`,
    `| ${header.map(() => "---").join(" | ")} |`,
    ...rows.map((r) => `| ${r.map(cell).join(" | ")} |`),
  ].join("\n");
}

function bullets(items: string[]): string {
  return items.map((i) => `- ${i.replace(/\r?\n/g, " ")}`).join("\n");
}

function isoDate(d: Date): string {
  return Number.isNaN(d.getTime()) ? "unknown date" : d.toISOString().slice(0, 10);
}

export function buildProjectBrief(run: AnalysisRun, opts: BriefOptions = {}): string {
  const { town, recommendation: rec, population } = run;
  const winner = run.winnerId ? run.candidates.find((c) => c.id === run.winnerId) ?? null : null;
  const partners = opts.partners ?? run.partners ?? [];
  const date = isoDate(opts.generatedAt ?? new Date(run.createdAt));
  const out: string[] = [];

  out.push(`# Water point project brief — ${town.displayName}`);
  out.push(
    `> Pre-feasibility desk study generated by Mayim on ${date} from a ${PROVENANCE_LABEL[run.provenance]}. ` +
      "Every figure is a planning range, not a quotation. A hydrogeological survey, pumping test, " +
      "water-quality test and community consultation are required before commitment.",
  );

  out.push("## Summary");
  out.push(run.narrative);

  // --- Proposed intervention ------------------------------------------------
  out.push("## Proposed intervention");
  if (!winner || !rec) {
    out.push(
      `No viable site was found: all ${num(run.candidateCount)} candidate sites near ${town.name} were excluded by a hard constraint.`,
    );
  } else {
    const cpp = costPerPersonServed(rec);
    const [lat, lon] = [winner.lat.toFixed(5), winner.lon.toFixed(5)];
    out.push(
      table(
        ["Item", "Estimate"],
        [
          ["System", rec.label],
          ["Site", `${lat}, ${lon} (${link("OpenStreetMap", `https://www.openstreetmap.org/?mlat=${lat}&mlon=${lon}#map=17/${lat}/${lon}`)})`],
          ["Suitability score", `${pct(winner.score.overall)} — ranked 1 of ${num(run.ranked.length)} viable sites (${num(run.excludedCount)} of ${num(run.candidateCount)} excluded)`],
          ["Capital cost", `${usd(rec.cost.totalLow)} – ${usd(rec.cost.totalHigh)}`],
          ...(cpp ? [["Cost per person served", `${usd(cpp.low)} – ${usd(cpp.high)} (capital only)`]] : []),
          ["Daily output", `${num(rec.output.dailyLitersLow)} – ${num(rec.output.dailyLitersHigh)} L/day`],
          ["People the system can supply", `${num(rec.peopleServedLow)} – ${num(rec.peopleServedHigh)} at ${rec.output.litersPerPersonPerDay} L/person/day`],
          ["People within reach", `${num(population.rangeLow)} – ${num(population.rangeHigh)} within ${num(population.serviceRadiusM)} m`],
          ["Implementation", `${rec.implementationRangeWeeks[0]}–${rec.implementationRangeWeeks[1]} weeks`],
          ["Maintenance burden", rec.maintenanceComplexity],
          ["Confidence", pct(rec.confidence)],
        ],
      ),
    );
    out.push(rec.coverageNote);

    if (rec.rationale.length) {
      out.push("### Why this system");
      out.push(bullets(rec.rationale));
    }
    if (rec.components.length) {
      out.push("### Components");
      out.push(bullets(rec.components.map((c) => `**${c.name}** — ${c.detail}`)));
    }

    out.push("### Cost breakdown");
    out.push(
      table(
        ["Line item", "Basis", "Low", "High", "Source"],
        [
          ...rec.cost.lineItems.map((li) => [li.label, li.formula, usd(li.low), usd(li.high), li.source]),
          ["Subtotal", "", usd(rec.cost.subtotalLow), usd(rec.cost.subtotalHigh), ""],
          ["Access multiplier", rec.cost.accessMultiplierReason, `×${rec.cost.accessMultiplier.toFixed(2)}`, "", ""],
          ["**Total**", "rounded", usd(rec.cost.totalLow), usd(rec.cost.totalHigh), ""],
        ],
      ),
    );
    out.push(`Water output: ${rec.output.formula}`);
  }

  // --- Why this site ----------------------------------------------------------
  if (run.whyThisSite.length) {
    out.push("## Why this site");
    out.push(bullets(run.whyThisSite.map((w) => `**${w.claim}** — ${w.basis}`)));
  }
  if (run.alternatives.length) {
    out.push("### Runner-up sites");
    out.push(bullets(run.alternatives.map((a) => `${a.candidateId}: ${a.comparison}`)));
  }

  // --- Population -------------------------------------------------------------
  out.push("## Population estimate");
  out.push(`${num(population.rangeLow)} – ${num(population.rangeHigh)} people (confidence ${pct(population.confidence)}). ${population.methodLabel}`);
  if (population.alternative) {
    out.push(
      `Cross-check from mapped buildings: ${num(population.alternative.rangeLow)} – ${num(population.alternative.rangeHigh)} people. ${population.alternative.methodLabel}`,
    );
  }

  // --- Evidence ---------------------------------------------------------------
  out.push("## Evidence");
  const evidenceFrom = EVIDENCE_LABEL[run.evidenceProvenance ?? "bundled"];
  if (run.findings.length === 0) {
    out.push("No external sources were retrieved; the analysis rests on mapped data only.");
  } else {
    out.push(`${run.findings.length} sources from ${evidenceFrom}.`);
    out.push(
      bullets(
        run.findings.map((f) => {
          const meta = [f.sourceName, f.publishedDate, `${pct(f.confidence)} confidence`].filter(Boolean).join(" · ");
          return `${link(f.title, f.sourceUrl)} — ${meta}. ${f.summary}`;
        }),
      ),
    );
  }

  // --- Partners ---------------------------------------------------------------
  if (partners.length) {
    out.push("## Organisations to approach");
    out.push(
      table(
        ["Organisation", "Type", "Focus", "Listing"],
        partners.map((p) => [
          link(p.name, p.countryUrl ?? p.url),
          p.kind,
          p.focus.map((f) => FOCUS_LABEL[f]).join(", ") || "—",
          p.source === "verified" ? `verified${p.lastVerified ? ` ${p.lastVerified}` : ""}` : "found by search, unreviewed",
        ]),
      ),
    );
  }

  for (const section of opts.extraSections ?? []) {
    out.push(`## ${section.title}`);
    out.push(section.body);
  }

  // --- Appendix ---------------------------------------------------------------
  if (rec?.requiredValidation.length) {
    out.push("## Required validation before commitment");
    out.push(bullets(rec.requiredValidation));
  }
  const assumptions = [...(rec?.assumptions ?? []), ...(rec?.cost.assumptions ?? [])];
  if (assumptions.length) {
    out.push("## Assumptions");
    out.push(bullets([...new Set(assumptions)]));
  }
  if (run.warnings.length) {
    out.push("## Warnings");
    out.push(bullets(run.warnings));
  }
  out.push("## Data sources");
  out.push(bullets(run.dataSources.map((d) => `${d.name} — ${d.ok ? "ok" : "unavailable"}: ${d.detail}`)));
  out.push(
    `---\n_Mayim pre-feasibility screening · run ${town.slug} · ${date}. OpenStreetMap data © OpenStreetMap contributors (ODbL)._`,
  );

  return `${out.join("\n\n")}\n`;
}
