/**
 * Saved live-evidence snapshots (data/evidence/<slug>.json).
 *
 * A snapshot is the output of a REAL Exa search for one town, saved with the
 * date it was retrieved. It is the middle rung between a live search and the
 * hand-written bundled placeholders: when the key is missing or Exa is down,
 * a demo town still shows genuine sources, labelled with their retrieval date.
 *
 * Written by `npm run evidence:refresh`, and by a town's first live run when it
 * has no snapshot yet. Live runs never overwrite an existing one.
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import type { EvidenceFinding, Partner } from "@/lib/types";
import type { QueryOutcome } from "@/lib/evidence/exa";

const EVIDENCE_DIR = path.join(process.cwd(), "data", "evidence");

export type EvidenceSnapshot = {
  version: 1;
  slug: string;
  displayName: string;
  /** ISO timestamp of the Exa search. */
  retrievedAt: string;
  /** "llm:<model>" or "deterministic". */
  structuredBy: string;
  queries: QueryOutcome[];
  findings: EvidenceFinding[];
  partners?: Partner[];
};

function fileFor(slug: string): string {
  // Slugs are generated by townSlug(), but never trust a path segment.
  const safe = slug.toLowerCase().replace(/[^a-z0-9-]/g, "");
  return path.join(EVIDENCE_DIR, `${safe}.json`);
}

export async function loadEvidenceSnapshot(slug: string): Promise<EvidenceSnapshot | null> {
  try {
    const parsed = JSON.parse(await fs.readFile(fileFor(slug), "utf8")) as EvidenceSnapshot;
    if (parsed?.version !== 1 || !Array.isArray(parsed.findings) || parsed.findings.length === 0) return null;
    return parsed;
  } catch {
    return null;
  }
}

/** Best-effort persist. A read-only filesystem (Vercel) must never break a run. */
export async function saveEvidenceSnapshot(snapshot: EvidenceSnapshot): Promise<boolean> {
  try {
    await fs.mkdir(EVIDENCE_DIR, { recursive: true });
    await fs.writeFile(fileFor(snapshot.slug), `${JSON.stringify(snapshot, null, 2)}\n`, "utf8");
    return true;
  } catch {
    return false;
  }
}

/** "15 Sep 2026" — for provenance labels. */
export function snapshotDateLabel(snapshot: EvidenceSnapshot): string {
  const d = new Date(snapshot.retrievedAt);
  if (Number.isNaN(d.getTime())) return "an earlier run";
  return d.toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" });
}
